name = "parsing-website"
main = "src/index.js"
compatibility_date = "2024-09-23"

# Serve static files
[assets]
directory = "./"
binding = "ASSETS"

# Variables (non-secrets)
[vars]
FRONTEND_URL = "https://parsing.co.za"
