name = "parsing-website"
main = "_worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./"
binding = "ASSETS"

[vars]
FRONTEND_URL = "https://parsing.co.za"
AUTH_WORKER_URL = "https://parsing-auth.buhle-1ce.workers.dev"
