name = "parsing-auth"
main = "index.js"
compatibility_date = "2024-09-23"

# KV Namespace for sessions
[[kv_namespaces]]
binding = "SESSIONS"
id = "a2130a9a4d1540a19510671b169db91d"

[vars]
FRONTEND_URL = "https://parsin